### ISSUE TITLE
Docs: Update Clear Walkthrough Instructions

### ISSUE THREAD

**Issue by hrittikhere** [harness-community/nodejs-pipeline-samples#9]
Hey @Ompragash / @codewdhruv 
I feel there should be more instructions on moving forward with this repository when a new user comes up. The current docs don't make it easy for anyone (including me) to complete the steps. 
Moreover, I have the following suggestions:
1. Add Source Code here for the app
2. Dockerfile here doesn't reflect the directory/code. An update should be made to reflect the same.
3. Steps should be easier with a walk-through in the repository 
4. If a blog backs this there should be some links.

CC: @pravindmali27

**Comment by Ompragash** [comment]
As you can see the `TODO` checklist in the README.md file, all the above suggestions are WIP by @codewdhruv!

Thanks for taking your time to go through this and the suggestions!
